### ISSUE TITLE
쿼리문 표현 수정요청

### ISSUE THREAD

**Issue by messi1913** [callakrsos/Gargoyle#11]
Select --> 예약어 표시 안됨. 
SELECT, select -> 예약어로 표시 됨. 

고쳐줭 토드는 됨.

**Comment by lake1310** [comment]
고쳐주세요~

**Comment by callakrsos** [comment]
정규식에 대소문자 구분을 무시하는 옵션추가 (?i)
![2](https://cloud.githubusercontent.com/assets/5085283/18027103/0a1895ae-6c95-11e6-8742-327a4bff666f.png)

**Comment by shadow5464** [comment]
예약어 관련 내용 퍼옴

1. SQL관련 예약어 조회
   ○ ORACLE DB에는 예약어가 존재하여 사용을 금지하거나, 사용을 권장하지 
      않는 단어가 있다. SYSDATE, DESC 등 이와 관련된 내용을 조회하는 view는
      다음과 같다
      - SELECT * FROM V$RESERVED_WORDS
