### ISSUE TITLE
DAO Wizard Location 저장시  사용자가 저장한 Workspace 제외 필요

### ISSUE THREAD

**Issue by shadow5464** [callakrsos/Gargoyle#15]
loaction 정보가 아래 와 같이 절대 경로로 저장됨.
D:\Meerkat1.0\workspace\sos-server\src\main\java\com\samsung\sds\sos\server\fx\dev\si\dao

위 경로 이외의 사람이 수정 할려면 따른곳에 저장 되거나 파일이 없는 오류 발생...

**Comment by callakrsos** [comment]
add by kyj.
저장시 아래 상대경로 단위로 저장되야함.
sos-server\src\main\java\com\samsung\sds\sos\server\fx\dev\si\dao

**Comment by callakrsos** [comment]
막상구현해보려니 상당히 어려운부분이 많음. OTL.
먼저 이걸 구현하는 쉬운 방법으로
패키지를 선택하고 DAOWizard를 진입할 수 있는 코드부분 작성이 선행되야할것으로 보임.

**Comment by shadow5464** [comment]
ValueUtil 에 2개의 메소드 추가하고 구현함..
패키지는 해당 프로젝트를 진행하는 모든 사람이 동일한 워크 스페이스를 가져 가야함.


public static String removeLocalLocation(String dir) {
		String classDirName = ResourceLoader.getInstance().get(ResourceLoader.BASE_DIR);
		return dir.replace(classDirName, "");
	}

	public static String addLocalLocation(String dir) {
		String classDirName = ResourceLoader.getInstance().get(ResourceLoader.BASE_DIR);

		return classDirName.concat(dir);
	}

**Comment by callakrsos** [comment]
흠, nice.
